version: '2'

services:
  pyapp:
    image: my_pyapp
    build: .
    ports:
      - '5000:5000'
    networks:
      - net1
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /root/data-dir:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: bridge
