version: '3.1'

services:
  pyapp:
    image: myapp:latest
    build: .
    ports:
      - '5000:5000'
    networks:
      - net1
    depends_on:
      - db
    healthcheck:
      interval: 30s
      retries: 3
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /home/marcelok/data-dir:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: overlay
