version: '3.1'

# docker image tag custom-nginx mkenjis/custom-nginx
# docker image tag myapp        mkenjis/myapp
# docker login
# docker push mkenjis/custom-nginx
# docker push mkenjis/myapp
# docker image rm -f mkenjis/custom-nginx
# docker image rm -f mkenjis/myapp

services:
  proxy:
    image: mkenjis/custom-nginx
    ports:
      - '443:443'
    networks:
      - net1
  pyapp:
    image: mkenjis/myapp
#    ports:
#      - '5000:5000'
    networks:
      - net1
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /root/data-dir:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: overlay
