version: '3.1'

services:
  proxy:
    image: nginx
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net1
  pyapp:
    image: myapp:latest
    build: .
#    ports:
#      - '5000:5000'
    networks:
      - net1
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /root/data-dir:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: bridge
